// Generated by scripts/scrape-announced.mjs — do not hand-edit.
// Source: https://www.applicantauction.com/announced-intended-applications
// Applicant Auction last updated: August 11, 2026

export type Announced = {
  lead: string;
  partners: string[];
  strings: string[];
  note: string | null; // set when the row names no concrete string
  withdrawnStrings: string[]; // subset of strings; empty when none were pulled
  withdrawnUrl: string | null; // where the withdrawal is recorded
  sourceUrl: string | null;
  sourceTitle: string;
  date: string;
};

export const announcedUpdated = "August 11, 2026";

export const announced: Announced[] = [
  {
    "lead": "Salesforce",
    "partners": [],
    "strings": [],
    "note": "dot-brand (exact string not stated)",
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31448-salesforce-to-apply-for-a-dot-brand",
    "sourceTitle": "Domain Incite: Salesforce to apply for a dot-brand",
    "date": "2026-06-30"
  },
  {
    "lead": "Nova Registry",
    "partners": [],
    "strings": [],
    "note": "200 new gTLDs (strings not disclosed)",
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/30879-nova-announces-45-million-of-new-gtld-applications",
    "sourceTitle": "Domain Incite: Nova announces $45 million of new gTLD applications",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "SHIB / Shiba Inu"
    ],
    "strings": [
      "shib"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29281-shiba-inu-outs-itself-as-crypto-new-gtld-applicant",
    "sourceTitle": "Domain Incite: Shiba Inu outs itself as crypto new gTLD applicant",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Gate.io"
    ],
    "strings": [
      "gate"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29423-another-crypto-firm-to-apply-for-a-new-gtld",
    "sourceTitle": "Domain Incite: Another crypto firm to apply for a new gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "NEAR Foundation"
    ],
    "strings": [
      "near"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29467-d3-announces-fourth-crypto-new-gtld-client",
    "sourceTitle": "Domain Incite: D3 announces fourth crypto new gTLD client",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Core Chain"
    ],
    "strings": [
      "core"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29511-d3-signs-up-crypto-gtld-client-number-five",
    "sourceTitle": "Domain Incite: D3 signs up crypto gTLD client number five",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "ApeCoin community / DAO"
    ],
    "strings": [
      "ape"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29736-d3-to-get-5-million-in-crypto-to-apply-for-ape-gtld",
    "sourceTitle": "Domain Incite: D3 to get $5 million in crypto to apply for .ape gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "MAKE",
      "Casper Foundation"
    ],
    "strings": [
      "cspr"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29827-d3-announces-seventh-blockchain-gtld-client",
    "sourceTitle": "Domain Incite: D3 announces seventh blockchain gTLD client",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Own The Doge / PleasrDAO"
    ],
    "strings": [
      "doge"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/30754-could-musks-doge-kill-off-d3s-doge",
    "sourceTitle": "Domain Incite: Could Musk’s DOGE kill off D3’s .doge?",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Animecoin Foundation",
      "Azuki"
    ],
    "strings": [
      "anime"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/30812-second-new-gtld-contention-set-revealed",
    "sourceTitle": "Domain Incite: Second new gTLD contention set revealed",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Viction"
    ],
    "strings": [
      "vic"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29281-shiba-inu-outs-itself-as-crypto-new-gtld-applicant",
    "sourceTitle": "Domain Incite: Shiba Inu outs itself as crypto new gTLD applicant",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Women in Tech Global"
    ],
    "strings": [
      "witg"
    ],
    "note": null,
    "withdrawnStrings": [
      "witg"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29859-unstoppable-to-apply-for-women-in-tech-gtld",
    "sourceTitle": "Domain Incite: Unstoppable to apply for Women in Tech gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "POG Digital"
    ],
    "strings": [
      "pog"
    ],
    "note": null,
    "withdrawnStrings": [
      "pog"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29859-unstoppable-to-apply-for-women-in-tech-gtld",
    "sourceTitle": "Domain Incite: Unstoppable to apply for Women in Tech gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Clay Nation"
    ],
    "strings": [
      "clay"
    ],
    "note": null,
    "withdrawnStrings": [
      "clay"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29859-unstoppable-to-apply-for-women-in-tech-gtld",
    "sourceTitle": "Domain Incite: Unstoppable to apply for Women in Tech gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Pudgy Penguins"
    ],
    "strings": [
      "pudgy"
    ],
    "note": null,
    "withdrawnStrings": [
      "pudgy"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29859-unstoppable-to-apply-for-women-in-tech-gtld",
    "sourceTitle": "Domain Incite: Unstoppable to apply for Women in Tech gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Kintsugi Global"
    ],
    "strings": [
      "manga",
      "anime"
    ],
    "note": null,
    "withdrawnStrings": [
      "manga"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29952-unstoppable-plotting-manga-themed-gtlds",
    "sourceTitle": "Domain Incite: Unstoppable plotting manga-themed gTLDs",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Raiinmaker Network"
    ],
    "strings": [
      "raiin"
    ],
    "note": null,
    "withdrawnStrings": [
      "raiin"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29993-unstoppable-announces-another-new-gtld-bid",
    "sourceTitle": "Domain Incite: Unstoppable announces another new gTLD bid",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Farmsent"
    ],
    "strings": [
      "farms"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/30152-unstoppable-reveals-gtld-bid-doomed-to-fail",
    "sourceTitle": "Domain Incite: Unstoppable reveals gTLD bid doomed to fail",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Secret Network Foundation"
    ],
    "strings": [
      "secret"
    ],
    "note": null,
    "withdrawnStrings": [
      "secret"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29926-secret-new-gtld-application-revealed",
    "sourceTitle": "Domain Incite: Secret new gTLD application revealed",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "0G Foundation"
    ],
    "strings": [
      "agi"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31315-ai-rival-lines-up-gtld-bid",
    "sourceTitle": "Domain Incite: .ai rival lines up gTLD bid",
    "date": "2026-06-30"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Metropolis"
    ],
    "strings": [
      "metropolis"
    ],
    "note": null,
    "withdrawnStrings": [
      "metropolis"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://domainincite.com/29907-first-metaverse-gtld-is-announced",
    "sourceTitle": "Domain Incite: First metaverse gTLD is announced",
    "date": "2026-06-30"
  },
  {
    "lead": "Freename.io",
    "partners": [],
    "strings": [
      "chain",
      "token",
      "metaverse"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/30290-is-this-the-first-next-round-new-gtld-contention-battle",
    "sourceTitle": "Domain Incite: Is this the first Next Round new gTLD contention battle?",
    "date": "2026-06-30"
  },
  {
    "lead": "3DNS",
    "partners": [],
    "strings": [
      "chain",
      "super"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/30290-is-this-the-first-next-round-new-gtld-contention-battle",
    "sourceTitle": "Domain Incite: Is this the first Next Round new gTLD contention battle?",
    "date": "2026-06-30"
  },
  {
    "lead": "The Reservoir Project / Child Online Safety Association",
    "partners": [],
    "strings": [
      "haven"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31654-kid-friendly-domains-could-be-reborn",
    "sourceTitle": "Domain Incite: Kid-friendly domains could be reborn",
    "date": "2026-06-30"
  },
  {
    "lead": "dottree.org project",
    "partners": [],
    "strings": [
      "tree"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31665-is-a-tree-gtld-very-cool-or-very-silly",
    "sourceTitle": "Domain Incite: Is a .tree gTLD very cool or very silly?",
    "date": "2026-06-30"
  },
  {
    "lead": "NIXI",
    "partners": [],
    "strings": [
      "india",
      "bharat"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31285-nixi-planning-doomed-new-gtld-bids",
    "sourceTitle": "Domain Incite: NIXI planning doomed new gTLD bids",
    "date": "2026-06-30"
  },
  {
    "lead": "DomainDAO",
    "partners": [],
    "strings": [
      "dao"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/28109-group-crowdfunding-crypto-to-apply-to-icann-for-blockchain-gtld",
    "sourceTitle": "Domain Incite: Group crowdfunding crypto to apply to ICANN for blockchain gTLD",
    "date": "2026-06-30"
  },
  {
    "lead": "D3 Global",
    "partners": [],
    "strings": [],
    "note": "multiple traditional TLDs (initially unspecified)",
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/29040-blockchain-startup-gets-5-million-to-apply-for-gtlds",
    "sourceTitle": "Domain Incite: Blockchain startup gets $5 million to apply for gTLDs",
    "date": "2026-06-30"
  },
  {
    "lead": "Human-Centered Computing Foundation",
    "partners": [],
    "strings": [
      "self"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31779-a-free-ethical-new-gtld-shurely-shome-mishtake",
    "sourceTitle": "Domain Incite: A free, ethical new gTLD? Shurely shome mishtake",
    "date": "2026-07-02"
  },
  {
    "lead": "Ethereum Name Service (ENS)",
    "partners": [],
    "strings": [
      "ens"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainnamewire.com/2026/03/18/ethereum-name-service-to-apply-for-ens-in-icann-top-level-domain-expansion/",
    "sourceTitle": "Domain Name Wire: Ethereum Name Service to apply for .ENS in ICANN top level domain expansion",
    "date": "2026-07-09"
  },
  {
    "lead": "dotMeow Foundation",
    "partners": [],
    "strings": [
      "meow"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainnamewire.com/2026/06/26/meow-core/",
    "sourceTitle": "Domain Name Wire: .Meow selects CORE, deals with new TLD headaches",
    "date": "2026-07-09"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Blockchain.com"
    ],
    "strings": [
      "blockchain"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainnamewire.com/2024/06/07/first-blockchain-applicant-steps-forward/",
    "sourceTitle": "Domain Name Wire: First .blockchain applicant steps forward",
    "date": "2026-07-09"
  },
  {
    "lead": ".twin project",
    "partners": [],
    "strings": [
      "twin"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://news.google.com/rss/articles/CBMihgJBVV95cUxPV0JNblA1WTFlV0w3ZXoxX0swWTVFZThPSzlUaGJMTUVsSFVPbTRUdkdWMzh1NHBmSTFHWjc5cFllcEtJb0pWZW9JSmVMbEJnTENVWndpTFd6aUROUjJ4aC04NXQtXzZVM3Q2cGJuYVk3SFBnVElNMWpFcmZVOEpLZC1LSzFzSEphZzJQWmhpTDNpWTJLSEFUdUpQZkJRenpHZ2RLMk9XcHBaS0FyZWliM3F6VmJMMFplMDZaRXIzQ2txNWJqMHkzN1J6V1NNZmM5dHRoQTNmNjB6UlR1dGJYVEx4QjVUMWhrOVd6NmdtMi1jdDZfM0VYLW9SY0pnUFd5cnJLTWp3?oc=5",
    "sourceTitle": "GlobeNewswire: .twin to Enter ICANN’s 2026 gTLD Application Round as Digital Twins Become Core to Global Infrastructure",
    "date": "2026-07-09"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Sentient Foundation"
    ],
    "strings": [
      "agent"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.globenewswire.com/news-release/2025/12/09/3202433/0/en/agent-intends-to-officially-enter-the-icann-application-process-with-unstoppable-domains-and-sentient-foundation.html",
    "sourceTitle": "GlobeNewswire: .agent Intends to Officially Enter the ICANN Application Process with Unstoppable Domains and Sentient Foundation",
    "date": "2026-07-11"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Hub Culture"
    ],
    "strings": [
      "hub"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.globenewswire.com/news-release/2026/01/05/3212830/0/en/unstoppable-domains-and-hub-culture-today-announced-their-intent-to-submit-hub-for-icann-s-upcoming-generic-top-level-domain-gtld-application-round.html",
    "sourceTitle": "GlobeNewswire: Unstoppable Domains and Hub Culture announced intent to submit .hub for ICANN's upcoming gTLD application round",
    "date": "2026-07-11"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "Cake Wallet"
    ],
    "strings": [
      "xmr"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.globenewswire.com/news-release/2026/03/17/3257578/0/en/unstoppable-domains-announces-cake-wallet-s-intent-to-apply-for-xmr-top-level-domain-in-icann-s-next-gtld-round.html",
    "sourceTitle": "GlobeNewswire: Unstoppable Domains Announces Cake Wallet’s Intent to Apply for .XMR Top-Level Domain in ICANN’s Next gTLD Round",
    "date": "2026-07-11"
  },
  {
    "lead": ".privacy team",
    "partners": [
      "Unstoppable Domains"
    ],
    "strings": [
      "privacy"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.globenewswire.com/news-release/2025/10/14/3166287/0/en/privacy-announces-intent-to-officially-enter-the-icann-application-process-with-unstoppable-domains.html",
    "sourceTitle": "GlobeNewswire: .Privacy Announces Intent to Officially enter the ICANN Application Process with Unstoppable Domains",
    "date": "2026-07-12"
  },
  {
    "lead": "Brave",
    "partners": [
      "Unstoppable Domains"
    ],
    "strings": [
      "brave"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.globenewswire.com/news-release/2025/05/20/3084964/0/en/brave-becomes-first-browser-to-launch-onchain-naming-service-unlocking-brave-for-over-85m-users.html",
    "sourceTitle": "GlobeNewswire: Brave Becomes First Browser to Launch Onchain Naming Service, Unlocking .brave for Over 85M Users",
    "date": "2026-07-12"
  },
  {
    "lead": "ATH Vodka",
    "partners": [
      "Unstoppable Domains"
    ],
    "strings": [
      "ath"
    ],
    "note": null,
    "withdrawnStrings": [
      "ath"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://www.globenewswire.com/news-release/2025/05/27/3088861/0/en/ath-vodka-and-unstoppable-domains-launch-ath-domain-merging-luxury-spirits-with-web3-innovation.html",
    "sourceTitle": "GlobeNewswire: ATH Vodka and Unstoppable Domains Launch .ATH Domain, Merging Luxury Spirits with Web3 Innovation",
    "date": "2026-07-12"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "XYO"
    ],
    "strings": [
      "depin",
      "xyo"
    ],
    "note": null,
    "withdrawnStrings": [
      "depin",
      "xyo"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://www.globenewswire.com/news-release/2025/05/06/3075116/0/en/depin-and-xyo-domains-launch-to-anchor-18-8b-market-and-first-depin-operating-system.html",
    "sourceTitle": "GlobeNewswire: .DEPIN and .XYO Domains Launch to Anchor $18.8B Market and First DePIN Operating System",
    "date": "2026-07-13"
  },
  {
    "lead": "Abion",
    "partners": [],
    "strings": [
      "abion"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://abion.com/abion-to-apply-for-abion-top-level-domain/",
    "sourceTitle": "Abion: Abion to Apply for .abion Top-Level Domain",
    "date": "2026-07-16"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Friends With Benefits"
    ],
    "strings": [
      "fwb"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.prnewswire.com/news-releases/friends-with-benefits-partners-with-d3-to-apply-for-fwb-top-level-domain-302212843.html",
    "sourceTitle": "PR Newswire: Friends With Benefits Partners With D3 To Apply For .fwb Top-Level Domain",
    "date": "2026-07-16"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Magic Eden"
    ],
    "strings": [
      "magic"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.prnewswire.com/news-releases/magic-eden-partners-with-d3-to-apply-for-magic-top-level-domain-302206122.html",
    "sourceTitle": "PR Newswire: Magic Eden Partners With D3 To Apply For .magic Top-Level Domain",
    "date": "2026-07-16"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Solana Foundation"
    ],
    "strings": [
      "sol",
      "solana"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.prnewswire.com/news-releases/d3-raises-25m-series-a-led-by-paradigm-announces-the-first-blockchain-for-internets-362m-domain-names-302362780.html",
    "sourceTitle": "PR Newswire: D3 Raises $25M Series A Led by Paradigm, Announces The First Blockchain for Internet's 362M+ Domain Names",
    "date": "2026-07-16"
  },
  {
    "lead": "D3 Global",
    "partners": [
      "Avalanche"
    ],
    "strings": [
      "avax"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.prnewswire.com/news-releases/d3-raises-25m-series-a-led-by-paradigm-announces-the-first-blockchain-for-internets-362m-domain-names-302362780.html",
    "sourceTitle": "PR Newswire: D3 Raises $25M Series A Led by Paradigm, Announces The First Blockchain for Internet's 362M+ Domain Names",
    "date": "2026-07-16"
  },
  {
    "lead": "Sphere Labs",
    "partners": [],
    "strings": [
      "ape"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainnamewire.com/2024/07/08/d3-applies-for-ape-and-magic-trademarks/",
    "sourceTitle": "Domain Name Wire: D3 applies for .ape and .magic trademarks",
    "date": "2026-07-16"
  },
  {
    "lead": "ShortDot",
    "partners": [],
    "strings": [],
    "note": "multiple gTLDs (strings not disclosed)",
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainnamewire.com/2026/05/11/acquiring-and-building-tlds-dnw-podcast-586/",
    "sourceTitle": "Domain Name Wire: Acquiring and building TLDs – DNW Podcast #586",
    "date": "2026-07-16"
  },
  {
    "lead": "Cardano Foundation",
    "partners": [],
    "strings": [
      "ada",
      "cardano"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://www.coinspeaker.com/cardano-foundation-gtld-ada-cardano/",
    "sourceTitle": "Coinspeaker: Cardano Foundation Applies for .ada & .cardano gTLDs",
    "date": "2026-08-11"
  },
  {
    "lead": "Unstoppable Domains",
    "partners": [
      "The Edge Of Company"
    ],
    "strings": [
      "podcast"
    ],
    "note": null,
    "withdrawnStrings": [
      "podcast"
    ],
    "withdrawnUrl": "https://support.unstoppabledomains.com/support/solutions/articles/48001275818-tld-s-not-going-to-icann-and-valid-for-refund",
    "sourceUrl": "https://unstoppabledomains.com/blog/categories/announcements/article/podcast-tld",
    "sourceTitle": "Unstoppable Domains: Amplify Your Voice and Contribute to the Conversation with .podcast",
    "date": "2026-08-11"
  },
  {
    "lead": "Bali Provincial Government",
    "partners": [
      "PANDI"
    ],
    "strings": [
      "bali"
    ],
    "note": null,
    "withdrawnStrings": [],
    "withdrawnUrl": null,
    "sourceUrl": "https://domainincite.com/31847-bali-to-apply-for-bali-and-the-dot-is-delightful",
    "sourceTitle": "Domain Incite: Bali to apply for .bali, and the dot is delightful",
    "date": "2026-08-11"
  }
];
